#WIFI CREDENTIALS
WIFI_SSID="surveillancevan"
WIFI_PASSWORD="nsaiswatching"

#MQTT CREDENTIALS
DEVICE_ID="XBX999"
AWS_IOT_ENDPOINT="a2jgs36qfd35dk-ats.iot.us-east-2.amazonaws.com"
CA_CERT_PATH="certs/AmazonRootCA1.pem"
DEVICE_CERT_PATH="certs/device.pem.crt"
DEVICE_PRIVATE_KEY_PATH="certs/private.pem.key"