#WIFI CREDENTIALS
WIFI_SSID="enter_your_ssid_here"
WIFI_PASSWORD="enter_your_password_here"

#MQTT CREDENTIALS
DEVICE_ID="your_device_id_here"
AWS_IOT_ENDPOINT="your_aws_endpoint_here"
CA_CERT_PATH="path_to_your_ca_cert_here"
DEVICE_CERT_PATH="path_to_your_device_cert_here"
DEVICE_PRIVATE_KEY_PATH="path_to_your_device_private_key_here"